### ISSUE TITLE
Order headphones + wireless mic?

### ISSUE THREAD

**Issue by timjzee** [Woseseltops/RU-HumLab-XR#11]
Headphones for use with headsets. Perhaps also need a wireless mic for better audio quality during motion capture.

**Comment by Woseseltops** [comment]
> Headphones for use with headsets.

Two requirements:
* Headphone jack
* I think 'in ear' headphone are not that hygienic (at least not with my ears ;) )

> Perhaps also need a wireless mic for better audio quality during motion capture:

Perhaps we can ask Bob here?

@timjzee if you can make a suggestion, I guess we can just ask Margret to order it?
